_target_: gild.workspace.train_bc_unet_hybrid_workspace.TrainBCUnetHybridWorkspace
output_dir: /media/yixuan_2T/diffusion_policy/data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
checkpoint:
  save_last_ckpt: true
  save_last_snapshot: false
  topk:
    format_str: epoch={epoch:04d}-test_mean_score={test_mean_score:.3f}.ckpt
    k: 5
    mode: max
    monitor_key: test_mean_score
dataloader:
  batch_size: 64
  num_workers: 2
  persistent_workers: false
  pin_memory: true
  shuffle: true
dataset_obs_steps: 2
ema:
  _target_: gild.model.diffusion.ema_model.EMAModel
  inv_gamma: 1.0
  max_value: 0.9999
  min_value: 0.0
  power: 0.75
  update_after_step: 0
exp_name: default
horizon: 16
keypoint_visible_rate: 1.0
logging:
  group: null
  id: null
  mode: online
  name: ${now:%Y.%m.%d}_train_diffusion_unet_hybrid_sapien_can_d3fields_mixed_demo_100
  project: diffusion_policy_${task_name}
  resume: false
  tags:
  - train_diffusion_unet_hybrid
  - sapien_can_image
  - default
multi_run:
  run_dir: data/outputs/${now:%Y.%m.%d}/train_diffusion_unet_hybrid_sapien_can_image
  wandb_name_base: ${now:%Y.%m.%d}-train_diffusion_unet_hybrid_sapien_can_image
n_action_steps: 8
n_latency_steps: 0
n_obs_steps: 2
name: train_diffusion_unet_hybrid
obs_as_global_cond: true
optimizer:
  _target_: torch.optim.AdamW
  betas:
  - 0.95
  - 0.999
  eps: 1.0e-08
  lr: 0.0001
  weight_decay: 1.0e-06
past_action_visible: false
policy:
  _target_: gild.policy.bc_unet_hybrid_image_policy.BCUnetHybridImagePolicy
  cond_predict_scale: true
  # NOTE: crop_shape needs to smaller than obs
  crop_shape:
  - 58
  - 78
  diffusion_step_embed_dim: 128
  down_dims:
  - 512
  - 1024
  - 2048
  eval_fixed_crop: true
  horizon: 16
  kernel_size: 5
  n_action_steps: 8
  n_groups: 8
  n_obs_steps: 2
  num_inference_steps: 100
  obs_as_global_cond: true
  obs_encoder_group_norm: true
  shape_meta:
    action:
      shape:
      - 10
    obs:
      # front_view_color:
      #   shape:
      #   - 3
      #   - 60
      #   - 80
      #   type: rgb
      # right_view_color:
      #   shape:
      #   - 3
      #   - 60
      #   - 80
      #   type: rgb
      ee_pos:
        shape:
        - 7
      # ee_vel:
      #   shape:
      #   - 7
      d3fields:
        shape:
        - 1027 # C
        - 200 # N
        type: spatial
        info:
          view_keys:
          - left_bottom_view
          - right_bottom_view
          - left_top_view
          - right_top_view
          query_texts:
          - soda
          - pad
          - table
          query_thresholds:
          - 0.3
          N_per_inst: 100
          boundaries:
            x_lower: -0.35
            x_upper: 0.35
            y_lower: -0.5
            y_upper: 0.5
            z_lower: -0.02
            z_upper: 0.4
          resize_ratio: 0.5
shape_meta:
  action:
    shape:
    - 10
  obs:
    # front_view_color:
    #   shape:
    #   - 3
    #   - 60
    #   - 80
    #   type: rgb
    # right_view_color:
    #   shape:
    #   - 3
    #   - 60
    #   - 80
    #   type: rgb
    ee_pos:
      shape:
      - 7
    # ee_vel:
    #   shape:
    #   - 7
    d3fields:
      shape:
      - 1027 # C
      - 200 # N
      type: spatial
      info:
        view_keys:
        - left_bottom_view
        - right_bottom_view
        - left_top_view
        - right_top_view
        query_texts:
        - soda
        - pad
        - table
        query_thresholds:
        - 0.3
        N_per_inst: 100
        boundaries:
          x_lower: -0.35
          x_upper: 0.35
          y_lower: -0.5
          y_upper: 0.5
          z_lower: -0.02
          z_upper: 0.4
        resize_ratio: 0.5
task:
  abs_action: true
  dataset:
    _target_: gild.dataset.sapien_dataset.SapienDataset
    dataset_dir: /media/yixuan_2T/diffusion_policy/data/sapien_env/teleop_data/pick_place_soda/mixed_demo_100
    horizon: 16
    pad_after: 7
    pad_before: 1
    rotation_rep: rotation_6d
    seed: 42
    shape_meta:
      action:
        shape:
        - 10
      obs:
        # front_view_color:
        #   shape:
        #   - 3
        #   - 60
        #   - 80
        #   type: rgb
        # right_view_color:
        #   shape:
        #   - 3
        #   - 60
        #   - 80
        #   type: rgb
        ee_pos:
          shape:
          - 7
        # ee_vel:
        #   shape:
        #   - 7
        d3fields:
          shape:
          - 1027 # C
          - 200 # N
          type: spatial
          info:
            view_keys:
            - left_bottom_view
            - right_bottom_view
            - left_top_view
            - right_top_view
            query_texts:
            - soda
            - pad
            - table
            query_thresholds:
            - 0.3
            N_per_inst: 100
            boundaries:
              x_lower: -0.35
              x_upper: 0.35
              y_lower: -0.5
              y_upper: 0.5
              z_lower: -0.02
              z_upper: 0.4
            resize_ratio: 0.5
    use_cache: true
    val_ratio: 0.1
  dataset_dir: /media/yixuan_2T/diffusion_policy/data/sapien_env/teleop_data/pick_place_soda/mixed_demo_100
  env_runner:
    _target_: gild.env_runner.sapien_series_image_runner.SapienSeriesImageRunner
    abs_action: true
    crf: 22
    dataset_dir: /media/yixuan_2T/diffusion_policy/data/sapien_env/teleop_data/pick_place_soda/mixed_demo_100
    fps: 10
    max_steps: 8
    n_action_steps: 8
    n_envs: null
    n_obs_steps: 2
    n_test: 1
    n_test_vis: 1
    n_train: 1
    n_train_vis: 1
    train_obj_ls:
    # - pepsi
    # - sprite
    # - obamna
    # - mtndew
    - cola
    test_obj_ls:
    - pepsi
    # - sprite
    - obamna
    - mtndew
    - cola
    past_action: false
    render_obs_keys:
    # - front_view
    # - right_view
    - left_bottom_view
    - right_bottom_view
    - left_top_view
    - right_top_view
    policy_keys:
    - d3fields
    - ee_pos
    shape_meta:
      action:
        shape:
        - 10
      obs:
        left_bottom_view_color:
          shape:
          - 3
          - 480
          - 640
          type: rgb
        right_bottom_view_color:
          shape:
          - 3
          - 480
          - 640
          type: rgb
        ee_pos:
          shape:
          - 7
        # ee_vel:
        #   shape:
        #   - 7
        d3fields:
          shape:
          - 1027 # C
          - 200 # N
          type: spatial
          info:
            view_keys:
            - left_bottom_view
            - right_bottom_view
            - left_top_view
            - right_top_view
            query_texts:
            - soda
            - pad
            - table
            query_thresholds:
            - 0.3
            N_per_inst: 100
            boundaries:
              x_lower: -0.35
              x_upper: 0.35
              y_lower: -0.5
              y_upper: 0.5
              z_lower: -0.02
              z_upper: 0.4
            resize_ratio: 0.5
    test_start_seed: 100000
    tqdm_interval_sec: 1.0
    train_start_idx: 0
  name: sapien_can_image
  shape_meta:
    action:
      shape:
      - 10
    obs:
      # front_view_color:
      #   shape:
      #   - 3
      #   - 60
      #   - 80
      #   type: rgb
      # right_view_color:
      #   shape:
      #   - 3
      #   - 60
      #   - 80
      #   type: rgb
      ee_pos:
        shape:
        - 7
      # ee_vel:
      #   shape:
      #   - 7
      d3fields:
        shape:
        - 1027 # C
        - 200 # N
        type: spatial
        info:
          view_keys:
          - left_bottom_view
          - right_bottom_view
          - left_top_view
          - right_top_view
          query_texts:
          - soda
          - pad
          - table
          query_thresholds:
          - 0.3
          N_per_inst: 100
          boundaries:
            x_lower: -0.35
            x_upper: 0.35
            y_lower: -0.5
            y_upper: 0.5
            z_lower: -0.02
            z_upper: 0.4
          resize_ratio: 0.5
  task_name: can
task_name: sapien_can_image
training:
  checkpoint_every: 50
  debug: false
  device: cuda
  device_id: 0
  gradient_accumulate_every: 1
  lr_scheduler: cosine
  lr_warmup_steps: 500
  max_train_steps: null
  max_val_steps: null
  num_epochs: 8000
  resume: false
  rollout_every: 50
  sample_every: 5
  seed: 42
  tqdm_interval_sec: 1.0
  use_ema: true
  val_every: 1
val_dataloader:
  batch_size: 64
  num_workers: 8
  persistent_workers: false
  pin_memory: true
  shuffle: false
